language: node_js
node_js:
  - 12.16.3
branches:
  only:
    - master
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: s3
  bucket: ${AWS_BUCKET}
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  cleanup: true
  local_dir: public
  acl: public_read

after_deploy:
  - ./node_modules/.bin/aws-cloudfront-invalidate ${CLOUDFRONT_DISTRIBUTION}
